const seed = {
  connectors: [
    {name:'Priya Sharma', audience:'VIT CSE, final year', channel:'Student ambassador', code:'PRIYA-VIT', unique:42, status:'Active'},
    {name:'Rohit Mehta', audience:'SRM placement group', channel:'Placement community', code:'ROHIT-SRM', unique:38, status:'Active'},
    {name:'TechSphere Club', audience:'MIT technical club', channel:'Technical club', code:'TECH-MIT', unique:35, status:'Active'},
    {name:'Ayesha Khan', audience:'BMSCE ISE, final year', channel:'Student ambassador', code:'AYESHA-BMS', unique:27, status:'Active'},
    {name:'CodeCraft Club', audience:'PESU coding community', channel:'Technical club', code:'CODE-PES', unique:0, status:'Pending'}
  ],
  registrations: [
    {name:'Ananya Rao', college:'VIT', branch:'CSE', source:'PRIYA-VIT', status:'Verified', time:'Sample record', email:'ananya@example.com'},
    {name:'Nikhil Verma', college:'SRM', branch:'IT', source:'ROHIT-SRM', status:'Verified', time:'Sample record', email:'nikhil@example.com'},
    {name:'Ishita Nair', college:'MIT', branch:'CSE', source:'TECH-MIT', status:'Verified', time:'Sample record', email:'ishita@example.com'},
    {name:'Arjun Pillai', college:'BMSCE', branch:'ISE', source:'AYESHA-BMS', status:'Verified', time:'Sample record', email:'arjun@example.com'}
  ], gross:361, baselineUnique:324, rejected:33, activeConnectorCount:18,
  sourceTotals:{'Student ambassador':145,'Technical club':112,'Placement community':71}
};
let state = JSON.parse(localStorage.getItem('nxtwave-console-v2') || 'null') || structuredClone(seed);
const $ = s => document.querySelector(s);
const $$ = s => document.querySelectorAll(s);
const escapeHTML = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function save(){ localStorage.setItem('nxtwave-console-v2', JSON.stringify(state)); }
function allUnique(){ return state.baselineUnique + state.registrations.filter(r=>r.status==='Verified').length; }
function codeFor(name,audience){ const left=name.split(' ')[0].replace(/[^a-z]/gi,'').slice(0,6).toUpperCase() || 'CAMPUS'; const right=(audience.match(/[A-Za-z]{2,}/g)||['LINK'])[0].slice(0,4).toUpperCase(); let code=`${left}-${right}`; let n=2; while(state.connectors.some(x=>x.code===code)) code=`${left}-${right}${n++}`; return code; }
function linkFor(code){ const link=new URL(location.href); link.searchParams.set('ref',code); link.hash='register'; return link.href; }
function updateDashboard(){ const unique=allUnique(), gross=state.gross, quality=(unique/gross*100).toFixed(1), inactive=Math.max(0,20-state.activeConnectorCount); $('#unique-total').textContent=unique; $('#metric-unique').textContent=unique; $('#metric-gross').textContent=gross; $('#metric-filtered').textContent=`${gross-unique} filtered for quality`; $('#metric-active').textContent=`${state.activeConnectorCount} / 20`; $('#metric-inactive').textContent=`${inactive} still need activation`; $('#action-title').textContent=inactive?`Activate ${inactive} more connector${inactive===1?'':'s'}`:'Keep active connectors engaged'; $('#metric-quality').textContent=`${quality}%`; $('#progress-bar').style.width=`${Math.min(unique/500*100,100)}%`; $('#progress-copy').textContent=unique>=500?'Simulated target reached.':`${500-unique} sample registrations to target`;
 const values=[32,70,119,171,235,Math.min(unique,328),unique]; $('#chart').innerHTML=values.map(v=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(8,v/Math.max(unique,328)*100)}%"><span>${v}</span></div></div>`).join('');
 const channels=[['Student ambassadors',state.sourceTotals['Student ambassador']],['Technical clubs',state.sourceTotals['Technical club']],['Placement communities',state.sourceTotals['Placement community']]]; const max=Math.max(...channels.map(x=>x[1])); $('#source-list').innerHTML=channels.map(([n,v])=>`<div class="source-row"><div class="source-title"><span>${n}</span><span>${v}</span></div><div class="source-track"><i style="width:${v/max*100}%"></i></div></div>`).join('');
}
function renderConnectors(){ $('#connectors-body').innerHTML=state.connectors.map((c,i)=>`<tr><td><b>${escapeHTML(c.name)}</b><small>${escapeHTML(c.audience)}</small></td><td>${escapeHTML(c.channel)}</td><td><span class="code">${escapeHTML(c.code)}</span></td><td><b>${c.unique}</b></td><td><span class="status ${c.status==='Pending'?'pending':''}">${escapeHTML(c.status)}</span></td><td><button class="row-button" data-kit="${i}">Open kit →</button></td></tr>`).join(''); $$('[data-kit]').forEach(b=>b.onclick=()=>openKit(state.connectors[+b.dataset.kit])); }
function renderRegistrations(){ $('#registrations-body').innerHTML=state.registrations.slice().reverse().map(r=>`<tr><td><b>${escapeHTML(r.name)}</b><small>${escapeHTML(r.email||'Synthetic prototype record')}</small></td><td>${escapeHTML(r.college)}<small>${escapeHTML(r.branch)}</small></td><td><span class="code">${escapeHTML(r.source)}</span></td><td><span class="status ${r.status==='Verified'?'':'pending'}">${escapeHTML(r.status)}</span></td><td>${escapeHTML(r.time)}</td></tr>`).join(''); }
function render(){ updateDashboard(); renderConnectors(); renderRegistrations(); }
function switchView(name){ $$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}-view`)); $$('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.view===name)); $('#page-title').textContent=({dashboard:'Overview',connectors:'Connectors',registrations:'Registrations'})[name]; location.hash=name; window.scrollTo(0,0); }
function openKit(c){ $('#kit-name').textContent=`${c.name.split(' ')[0]}'s referral kit`; $('#kit-code').textContent=c.code; $('#kit-link').value=linkFor(c.code); $('#kit-message').value=`Hey! I found a free NxtWave workshop for final-year engineering students: “Build Your First AI Project in 60 Minutes.”\n\nYou’ll build a small AI project and leave with a portfolio next step. Register here: ${linkFor(c.code)}`; $('#open-kit-registration').onclick=()=>{ $('#kit-modal').close(); openStudent(c.code); }; $('#kit-modal').showModal(); }
function openStudent(ref){ const c=state.connectors.find(x=>x.code===ref); $('#student-form').reset(); $('#student-form').dataset.ref=ref||''; $('#form-referrer').textContent=c?c.name:'Campus connector'; $('#student-modal').showModal(); }
function showResult(status, name){ const valid=status==='Verified'; $('#result-icon').textContent=valid?'✓':'!'; $('#result-icon').style.background=valid?'#e6f8f5':'#fff2e6'; $('#result-icon').style.color=valid?'#03ab9d':'#c8752e'; $('#result-eyebrow').textContent=valid?'SAMPLE REGISTRATION RECORDED':'QUALITY CHECK COMPLETE'; $('#result-title').textContent=status==='Duplicate'?'Already counted.':status==='Ineligible'?'Not eligible in this scenario.':'Sample seat recorded.'; $('#result-copy').textContent=status==='Duplicate'?`${name}, this sample email is already registered. The unique total did not change.`:status==='Ineligible'?`${name}, this graduation year is outside the sample final-year audience. The unique total did not change.`:`${name}, the sample source and eligibility were recorded in this browser.`; $('#result-modal').showModal(); }
$$('[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();switchView(a.dataset.view)}); $$('[data-view-target]').forEach(a=>a.onclick=()=>switchView(a.dataset.viewTarget));
$('#new-connector').onclick=$('#new-connector-2').onclick=()=>$('#connector-modal').showModal(); $('#open-student-form').onclick=()=>openStudent('PRIYA-VIT');
$('#connector-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),name=d.get('name'),audience=d.get('audience');const c={name,audience,channel:d.get('channel'),code:codeFor(name,audience),unique:0,status:'Pending'};state.connectors.unshift(c);save();render();$('#connector-modal').close();openKit(c)});
$('#student-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),email=d.get('email').trim().toLowerCase(),name=d.get('studentName').trim(),ref=e.currentTarget.dataset.ref||'DIRECT'; if(!email.endsWith('@example.com')){alert('Use a sample @example.com email for this sandbox.');return;} const status=state.registrations.some(r=>r.email===email)?'Duplicate':d.get('year')==='2027'?'Verified':'Ineligible'; state.gross++;if(status!=='Verified')state.rejected++;state.registrations.push({name,college:d.get('college'),branch:d.get('branch'),source:ref,status,time:'Just now',email});if(status==='Verified'){const c=state.connectors.find(x=>x.code===ref);if(c){if(c.status==='Pending')state.activeConnectorCount++;c.unique++;c.status='Active';state.sourceTotals[c.channel]++;}}save();render();$('#student-modal').close();showResult(status,name);});
$$('[data-copy]').forEach(b=>b.onclick=async()=>{const input=$('#'+b.dataset.copy); await navigator.clipboard.writeText(input.value); const old=b.textContent;b.textContent='Copied';setTimeout(()=>b.textContent=old,1200)}); $('#reset-data').onclick=()=>{localStorage.removeItem('nxtwave-console-v2');state=structuredClone(seed);render();}; $('#open-kit-registration').onclick=()=>openStudent('PRIYA-VIT');
const ref=new URLSearchParams(location.search).get('ref'); if(location.hash==='#register') setTimeout(()=>openStudent(ref),300); render();
